annotations:
  category: Infrastructure

apiVersion: v2
name: cells
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v4"

home: https://pydio.com
icon: https://pydio.com/sites/all/themes/pydio_theme/images/logoPydioWhite.png

sources:
  - https://github.com/pydio/cells

maintainers:
  - name: Pydio
    url: https://github.com/pydio/cells/tools/kubernetes

keywords:
  - pydio
  - cells
  - storage
  - object-storage
  - s3
  - cluster

dependencies:
  - name: mariadb
    condition: mariadb.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 20.5.5
  - name: mariadb-galera
    condition: mariadb-galera.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 14.2.9
  - name: redis
    condition: redis.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 21.x.x
  - name: nats
    condition: nats.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 9.0.17
  - name: mongodb
    condition: mongodb.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 16.5.23
  - name: etcd
    condition: etcd.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 11.3.x
  - name: minio
    condition: minio.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 17.0.6
  - name: ingress-nginx
    condition: ingress.enabled
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.12.3
  - name: vault  
    condition: vault.enabled
    repository: https://helm.releases.hashicorp.com
    version: x.x.x
  - name: cert-manager
    condition: tls.enabled
    repository: https://charts.jetstack.io
    version: x.x.x

