# This is the minimal configuration to directly start a pre-configured server in sandbox mode.
# Simply run 'docker-compose up -d', you can log in with admin/admin at 
# http://localhost:8081 *and* https://localhost:8082 (after accepting the self-signed certificate)

proxyconfigs:
  - binds:
      - 0.0.0.0:8081
    reverseproxyurl: http://localhost:8081
  - binds:
      - 0.0.0.0:8082
    reverseproxyurl: https://localhost:8082
    tlsconfig:
      selfsigned:
        hostnames:
          - localhost


# Adapt to your convenience and report to the documentation to explore further possibilities.

# WebUI Admin definition
frontendlogin: admin
frontendpassword: admin

# DB connection
dbconnectiontype: tcp
dbtcphostname: mysql
dbtcpport: 3306
dbtcpname: cells
dbtcpuser: pydio
dbtcppassword: ChangeMe!
