version: "3"

services:

  cells:
    image: pydio/cells:unstable
    restart: always
    ports: ["80:80", "443:443"]
    environment:
      - CELLS_WORKING_DIR=/var/cells
      - CELLS_INSTALL_YAML=/pydio/config/install.yml
    volumes: 
      - "cellsdir:/var/cells"
      - "./data:/var/cells/data"
      - "./config:/pydio/config"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: pydio
    volumes:
      - "mysqldir:/var/lib/mysql"
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
      ]

volumes:
  cellsdir: {}
  mysqldir: {}
