name: main

#--------------------------------------------
# Default variables
#--------------------------------------------
bind: &bind {{ .BindHost }}
advertise: &advertise {{ .AdvertiseHost }}

#--------------------------------------------
# Default connection to runtime functions
#--------------------------------------------
connections: &connections
  config:
    uri: xds://default.cells.com/cells
  registry:
    uri: xds://default.cells.com/cells
  broker:
    uri: xds://default.cells.com/cells
  logs:
    uri: file://stdout

#--------------------------------------------
# Default servers configuration
#--------------------------------------------
servers: &servers
  grpc:
    bind: *bind
    advertise: *advertise
    port: 0
  grpc_discovery:
    bind: *bind
    advertise: *advertise
    port: 0
  http:
    bind: *bind
    advertise: *advertise
    type: http
    port: 0

#--------------------------------------------
# Default env configuration
#--------------------------------------------
env: &env
  CELLS_USE_REGISTRY_SESSION: true
  GRPC_EXPERIMENTAL_XDS_FEDERATION: true
  GRPC_XDS_BOOTSTRAP_CONFIG: {
    "xds_servers": [
      {
        "server_uri": "{{ .AdvertiseHost }}:{{ .DiscoveryPort }}",
        "server_features": [
          "xds_v3"
        ],
        "channel_creds": [
          {
            "type": "insecure"
          }
        ]
      }
    ],
    "client_default_listener_resource_name_template": "xdstp://default.cells.com/envoy.config.listener.v3.Listener/grpc/client/%s",
    "server_listener_resource_name_template": "xdstp://default.cells.com/envoy.config.listener.v3.Listener/grpc/server/%s",
    "node": {
      "id": "test-id",
      "locality": {
        "zone": "us-central1-a"
      }
    },
    "authorities": {
      "default.cells.com": {
        "client_listener_resource_name_template": "xdstp://default.cells.com/envoy.config.listener.v3.Listener/grpc/client/%s"
      },
      "tenant.cells.com": {
        "client_listener_resource_name_template": "xdstp://tenant.cells.com/envoy.config.listener.v3.Listener/grpc/client/%s",
        "server_listener_resource_name_template": "xdstp://tenant.cells.com/envoy.config.listener.v3.Listener/grpc/server/%s",
        "xds_servers": [
          {
            "server_uri": "127.0.0.1:8130",
            "server_features": [
              "xds_v3"
            ],
            "channel_creds": [
              {
                "type": "insecure"
              }
            ]
          }
        ]
      }
    }
  }

#--------------------------------------------
# All processes
#--------------------------------------------
processes:
  discovery:
    connections:
      <<: *connections
      config:
        uri: {{ .ConfigURL }}
      registry:
        uri: {{ .RegistryURL }}
      broker:
        uri: {{ .BrokerURL }}

    servers:
      <<: *servers
      grpc_discovery:
        port: {{ .DiscoveryPort }}
      http:
        type: caddy
        port: {{ .FrontendPort }}

    env: *env

    services:
      discovery:
      gateway:
      idm:
      frontend:
      data:
      scheduler:
      auth:
      broker:

#  idm:
#    connections: *connections
#    servers:
#      <<: *servers
#      http:
#        type: caddy
#        port: {{ .FrontendPort }}
#
#    env: *env
#    services:
#      gateway:
#      idm:
#      frontend:
#      data:
#      scheduler:
#
#  auth:
#    connections: *connections
#    servers: *servers
#    env: *env
#    services:
#      auth:
#
#  broker:
#    connections: *connections
#    servers: *servers
#    env: *env
#    services:
#      broker:

  datasource-peer:
    connections: *connections
    servers: *servers
    env: *env

    services:
      datasource:
        - pydio.grpc.data.objects.peer

  {{ if .Config }}
  {{ $objectsVal := .Config.Val "services/pydio.grpc.data.objects/sources" }}
  {{ $ := .Config }}
  {{ range $objectsVal.StringArray }}
  {{ if or (lt (len .) 8) (ne (slice . 0 8) ("updated:")) }}
  {{ if not ($.Val "services" (print "pydio.grpc.data.objects." .) "Disabled").Bool }}
  objects-{{ . }}:
    connections: *connections
    servers: *servers
    env: *env

    services:
      datasource:
        - pydio.grpc.data.objects.{{ . }}
  {{ end }}
  {{ end }}
  {{ end }}

  {{ $indexesVal := .Config.Val "services/pydio.grpc.data.index/sources" }}
  {{ $ := .Config }}
  {{ range $indexesVal.StringArray }}
  {{ if or (lt (len .) 8) (ne (slice . 0 8) ("updated:")) }}
  {{ if not ($.Val "services" (print "pydio.grpc.data.index." .) "Disabled").Bool }}
  index-{{ . }}:
    connections: *connections
    servers: *servers
    env: *env

    services:
      datasource:
        - pydio.grpc.data.index.{{ . }}
        - pydio.grpc.data.sync.{{ . }}
  {{ end }}
  {{ end }}
  {{ end }}
  {{ end }}
